### ISSUE TITLE
Thumbnail images not working

### ISSUE THREAD

**Issue by JoshuaJSlone** [kevincox/youtube-e2l#12]
Seems like very recently the thumbnail images have stopped showing, instead giving what seems like an error image. The links still work correctly, though.
![thumberror](https://cloud.githubusercontent.com/assets/11825349/7520480/0170d9ba-f4b5-11e4-8e91-3a48d13b8b2e.jpg)

**Comment by kevincox** [comment]
Yes, version 2 of the youtube API has been turned off.  The extension will need to be updated to version 3.  I will start working on it when I get the chance. If anyone wants to help they can feel free.

**Comment by AlexVallat** [comment]
Sadly, Google appear to have added a requirement for an API key to the v3 API, even to access such basic data as a title and a thumbnail. As API keys are rather unfriendly, and inherently unsuitable for open source client side applications, you might be better off using an alternative. Luckily, youtube provide an oEmbed API, which is good enough. The only thing you lose is the different qualities of thumbnail to pick from.

I've created a pull request with these changes - I've only done very limited testing, though.

If you can't live without thumbnail qualities, you could simply ignore the API provided thumbnail and fetch ``` https://i.ytimg.com/vi/{VIDEO_ID}/{QUALITY}default.jpg ``` where {QUALITY} is one of "", "mq", "hq", "sd", or "maxres", but who knows whether that might change in the future.

**Comment by kevincox** [comment]
Having the API key is not a problem, as Google provides "Browser Keys" that they know will not be kept secret.  I am working on a version using v3 right now.  I should have a test package up soon.

**Comment by kevincox** [comment]
Could you give this executable a try and see if it works for you?  If it does I'll reaease it to AMO.

https://addons.mozilla.org/en-US/firefox/addon/youtube-embed2link/versions/?page=1#version-1.9.7pre

Thanks again for the patch for oEmbed but I decided it would be better to go for the officially supported API.

**Comment by AlexVallat** [comment]
Yes, that seems to work just fine for me, thanks. If you're happy with using an API key, then fair enough. I'll keep the oEmbed branch around a little while just in case e2l is too popular for google's liking, or the key is too public or anything - I really don't trust API keys!

**Comment by AlexVallat** [comment]
Oh, just to mention, I tested on Firefox 38 on Desktop and 37 on Andriod. The AMO listing states that it only works up to version 30.0a1 of Firefox for Android, but I can confirm it works fine in 37, if you'd like to update the listing.

**Comment by kevincox** [comment]
On May 11, 2015 3:17 AM, "AlexVallat" <notifications@github.com> wrote:
>
> Yes, that seems to work just fine for me, thanks.

Awesome!  I'll release it tonight.

> If you're happy with using an API key, then fair enough. I'll keep the
oEmbed branch around a little while just in case e2l is too popular for
google's liking, or the key is too public or anything - I really don't
trust API keys!

Yeah, it is kinda weird to use a key that is made public.  But at least
Google understands what is going on so it shouldn't be a problem.

Thanks for keeping that branch around, I'll probably pull it into a branch
on my repo as well.  It's good to have the fallback just in case.

**Comment by kevincox** [comment]
On May 11, 2015 3:23 AM, "AlexVallat" <notifications@github.com> wrote:
>
> Oh, just to mention, I tested on Firefox 38 on Desktop and 37 on Andriod.
The AMO listing states that it only works up to version 30.0a1 of Firefox
for Android, but I can confirm it works fine in 37, if you'd like to update
the listing.
>

Ok good to know.  The version numbers are set by the packaging tool so
sometimes they are wonky and sometimes AMO won't let me change them but I
will see what I can do to get it marked as compatible.

**Comment by kevincox** [comment]
New version 1.8.9 has been uploaded to AMO pending review.
